from django.db import models

from deptx.helpers import generateUUID, now, random_chars
from deptx import friendly_id

from django_extensions.db.fields import CreationDateTimeField, ModificationDateTimeField
import json

class Provenance(models.Model):
    TYPE_NONE = 0
    TYPE_CRON = 1
    TYPE_MOP_TEMPLATE = 2
    TYPE_MOP_INSTANCE = 3
    
    CHOICES_TYPE = (
        (TYPE_NONE, "NONE"),
        (TYPE_CRON, "CRON"),
        (TYPE_MOP_TEMPLATE, "MOP_TEMPLATE"),
        (TYPE_MOP_INSTANCE, "MOP_INSTANCE"),
    )
    
    name = models.CharField(max_length=128)
    store_id = models.IntegerField(blank=True, null=True)
    
    type = models.IntegerField(choices=CHOICES_TYPE, default=TYPE_NONE)
    
    attribute1 = models.CharField(max_length=1024, blank=True, null=True)
    attribute2 = models.CharField(max_length=1024, blank=True, null=True)
    
    serial = models.SlugField(max_length=36, blank=True, null=True, unique=True, help_text="leave blank to have it generated by system")
       
    createdAt = CreationDateTimeField()
    modifiedAt = ModificationDateTimeField()
    
    @property
    def incon(self):
        attributes = []
        try:
            json1 = json.loads(self.attribute1)
            for j in json1:
                attributes.append(nicer(j))
            json2 = json.loads(self.attribute2)
            for j in json2:
                attributes.append(nicer(j))
    
            return sorted(attributes)
        except:
            return "ERROR"
 
    
    def save(self, *args, **kwargs):
        super(Provenance, self).save(*args, **kwargs)
        if self.id and not self.serial:
            self.serial = "%s%s%s" % (random_chars(size=3), friendly_id.encode(self.id), random_chars(size=3))
            super(Provenance, self).save(*args, **kwargs)
    
    def __unicode__(self):
        return "%s - %s - store: %d (%s)" % (self.get_type_display(), self.name, self.store_id, self.serial)


def nicer(j):
    crap, n = j['node'].split(":",1)
    crap, a = j['attribute'].split(":",1)
    nice = n + "." + a
    return nice.encode('ascii','ignore') 