from django.db import models

from players.models import Mop
from assets.models import Unit, Requisition, CronDocument, MopDocument
from django_extensions.db.fields import CreationDateTimeField, ModificationDateTimeField
from provmanager.models import Provenance
from mop.clearance import Clearance, convertTrustIntoClearance
import deptx.friendly_id as friendly_id
import re
from django.template import Context, loader, Template
from django.core.exceptions import ValidationError
from django.contrib import messages


class TrustTracker(models.Model):
    
    TUTORIAL_0_START = 0
    TUTORIAL_1_SENT_HOW_TO_REQUEST_FORM = 10
    TUTORIAL_2_SENT_HOW_TO_REQUEST_DOCUMENT = 20
    TUTORIAL_3_SENT_HOW_TO_CHECK_PROVENANCE = 30
    TUTORIAL_4_SENT_HOW_TO_SUBMIT_DOCUMENT = 40
    TUTORIAL_5_SENT_CONCLUSION = 50
    TUTORIAL_6_DONE = 60

    
    CHOICES_TUTORIAL = (
        (TUTORIAL_0_START, 'TUTORIAL_0_START'),
        (TUTORIAL_1_SENT_HOW_TO_REQUEST_FORM, 'TUTORIAL_1_SENT_HOW_TO_REQUEST_FORM'),
        (TUTORIAL_2_SENT_HOW_TO_REQUEST_DOCUMENT, 'TUTORIAL_2_SENT_HOW_TO_REQUEST_DOCUMENT'),
        (TUTORIAL_3_SENT_HOW_TO_CHECK_PROVENANCE, 'TUTORIAL_3_SENT_HOW_TO_CHECK_PROVENANCE'),
        (TUTORIAL_4_SENT_HOW_TO_SUBMIT_DOCUMENT, 'TUTORIAL_4_SENT_HOW_TO_SUBMIT_DOCUMENT'),
        (TUTORIAL_5_SENT_CONCLUSION, 'TUTORIAL_5_SENT_CONCLUSION'),
        (TUTORIAL_6_DONE, 'TUTORIAL_6_DONE'),
    )
    
    
    
    createdAt = CreationDateTimeField()
    modifiedAt = ModificationDateTimeField()
    
    mop = models.OneToOneField(Mop, related_name="trustTracker")
    trust = models.IntegerField(default=0)
    totalTrust = models.IntegerField(default=0)
    allowance = models.IntegerField(default=0)
    clearance = models.IntegerField(choices=Clearance.CHOICES_CLEARANCE_ALL, default=Clearance.CLEARANCE_LOW)
    
    tutorial = models.IntegerField(choices=CHOICES_TUTORIAL, default=TUTORIAL_0_START)
    tutorialProvErrors = models.IntegerField(default=0)
    
    
    def getCssUrl(self):
        return Clearance(self.clearance).getCssUrl()
    
    def getMailUrl(self):
        return Clearance(self.clearance).getMailUrl()
    
    def getBadgeUrl(self):
        return Clearance(self.clearance).getBadgeUrl()
    
    def addTrust(self, trust):
        self.totalTrust += trust
        self.trust += trust
        self.save()
    
    def isTutorial(self):
        if self.tutorial == self.TUTORIAL_6_DONE:
            return False
        else:
            return True
    
    def __unicode__(self):
        return "%s %s %s" % (self.mop.user.username, self.trust, self.get_clearance_display())

class TrustInstance(models.Model):
    createdAt = CreationDateTimeField()
    modifiedAt = ModificationDateTimeField()

    mop = models.ForeignKey(Mop)
    trust = models.IntegerField(default=0)
    clearance = models.IntegerField(choices=Clearance.CHOICES_CLEARANCE_ALL, default=Clearance.CLEARANCE_LOW, help_text="will be overridden when saved")
    
    def allowance(self):
        allowance = int(self.trust * 0.1)
        if allowance <0:
            allowance = 0
        return allowance
    
    def convertTrustIntoClearance(self):
        return convertTrustIntoClearance(self.trust)
    
    def getBadgeUrl(self):
        return Clearance(self.clearance).getBadgeUrl()
    
    def save(self, *args, **kwargs):
        self.clearance = self.convertTrustIntoClearance()
        super(TrustInstance, self).save(*args, **kwargs)    
    
    def __unicode__(self):
        return "%s - %s - %s" % (self.createdAt, self.mop.user.username, self.trust)
    



class RandomizedDocument(models.Model):
    mopDocument = models.ForeignKey(MopDocument)
    provenance = models.OneToOneField(Provenance, related_name="randomizedDocument")
    serial = models.CharField(max_length=36, blank=True, null=True, unique=True, help_text="leave blank, will be generated by system")
    isTutorial = models.BooleanField(default=False)
    #TODO/PERHAPS replace with Due-date
    active = models.BooleanField(default=True)
    createdAt = CreationDateTimeField()
    modifiedAt = ModificationDateTimeField()
    
    def __unicode__(self):
        if self.active == True:
            active = "ACTIVE"
        else:
            active = "INACTIVE"
        return "%s: %s (%s)" % (active, self.serial, self.mopDocument.provenance.name)
    
    def getBadgeUrl(self):
        return Clearance(self.mopDocument.clearance).getBadgeUrl()
    
    def clean(self, *args, **kwargs):
        if self.isTutorial:
            try:
                randomizedDocument = RandomizedDocument.objects.get(isTutorial=True)
                if not self == randomizedDocument:
                    raise ValidationError('You can only have one document for the tutorial! Change document %s first!' % randomizedDocument.serial)
            except RandomizedDocument.DoesNotExist:
                pass
        super(RandomizedDocument, self).clean(*args, **kwargs)

    def full_clean(self, *args, **kwargs):
        return self.clean(*args, **kwargs)
    
    def save(self, *args, **kwargs):
        self.full_clean()
        super(RandomizedDocument, self).save(*args, **kwargs)
        if self.id and not self.serial:
            self.serial = Clearance(self.mopDocument.clearance).generateSerial(self.mopDocument)
            super(RandomizedDocument, self).save()
    
class MopDocumentInstance(models.Model):
    STATUS_ACTIVE = 0
    STATUS_REPORTED = 1
    STATUS_REVOKED = 3
    STATUS_HACKED = 4
     
    CHOICES_STATUS = (
        (STATUS_ACTIVE, "active"),
        (STATUS_REPORTED, "reported"),
        (STATUS_REVOKED, "revoked"),
        (STATUS_HACKED, "hacked"),
    )
    
    TYPE_MOP = 0
    TYPE_CRON = 1
    
    CHOICES_TYPE = (
        (TYPE_MOP, "MOP"),
        (TYPE_CRON, "CRON"),
    )

    createdAt = CreationDateTimeField()
    modifiedAt = ModificationDateTimeField()
    
    mop = models.ForeignKey(Mop)
    status = models.IntegerField(choices=CHOICES_STATUS, default=STATUS_ACTIVE)
    modified = models.BooleanField(default=False)
    used = models.BooleanField(default=False)
    correct = models.BooleanField(default=False)
    provenanceState = models.TextField(blank=True, null=True)

    #stuff needed if it is a mop-document or cron-document
    type = models.IntegerField(choices=CHOICES_TYPE, default=TYPE_MOP)
    randomizedDocument = models.ForeignKey(RandomizedDocument, blank=True, null=True)
    cronDocument = models.ForeignKey(CronDocument, blank=True, null=True)
    
    def getClearance(self):
        if self.type == self.TYPE_CRON:
            return self.cronDocument.clearance
        else:
            return self.randomizedDocument.mopDocument.clearance
    
    def getTrustFinal(self):
        clearance = Clearance(self.getClearance())
        if self.status == self.STATUS_REPORTED:
            if self.correct:
                return clearance.getTrustReportedCorrect()
            else:
                return clearance.getTrustReportedIncorrect()
        elif self.status == self.STATUS_REVOKED:
            return clearance.getTrustRevoked()
        else:
            return 0
    
    def getTrustRequested(self):
        clearance = Clearance(self.getClearance())
        return clearance.getTrustRequested()

    def getDocumentSerial(self):
        if self.type == self.TYPE_MOP:
            return self.randomizedDocument.serial
        else:
            return self.cronDocument.serial

    def __unicode__(self):
        return "%s" % (self.getDocumentSerial())
        
class RequisitionBlank(models.Model):
    mop = models.ForeignKey(Mop)
    requisition = models.ForeignKey(Requisition)
    createdAt = CreationDateTimeField()
    modifiedAt = ModificationDateTimeField()
    
    def __unicode__(self):
        return self.requisition.name + " - " + self.mop.user.username 

class RequisitionInstance(models.Model):
    blank = models.ForeignKey(RequisitionBlank)
    data = models.CharField(max_length=256, blank=True, null=True)
    used = models.BooleanField(default=False)
    createdAt = CreationDateTimeField()
    modifiedAt = ModificationDateTimeField()
    serial = models.CharField(max_length=36, blank=True, null=True, unique=True, help_text="leave blank, will be generated by system")
    
    def __unicode__(self):
        return "%s-%s" % (self.blank.requisition.serial, self.serial)
    
    def save(self, *args, **kwargs):
        self.data = re.sub("[^0-9A-Za-z-]", "", self.data)
        super(RequisitionInstance, self).save(*args, **kwargs)
        if self.id and not self.serial:
            self.serial = "%s" % (friendly_id.encode(self.id))
            super(RequisitionInstance, self).save(*args, **kwargs)

class Mail(models.Model):
    TYPE_RECEIVED = 0
    TYPE_SENT = 1
    TYPE_DRAFT = 2
    
    CHOICES_TYPE = (
        (TYPE_RECEIVED, "sent by unit"),
        (TYPE_SENT, "sent by player"),
        (TYPE_DRAFT, "draft")
    )
    
    STATE_NORMAL = 0
    STATE_TRASHED = 1
    STATE_DELETED = 2
    
    CHOICES_STATE = (
        (STATE_NORMAL, "normal"),
        (STATE_TRASHED, "trashed"),
        (STATE_DELETED, "deleted")
    )
  
    SUBJECT_EMPTY = 1
    
    SUBJECT_REQUEST_FORM = 101
    SUBJECT_REQUEST_DOCUMENT = 103
    SUBJECT_SUBMIT_DOCUMENT = 104
        
    SUBJECT_RECEIVE_FORM = 201
    SUBJECT_RECEIVE_DOCUMENT = 203
    
    SUBJECT_ERROR = 211
    SUBJECT_INFORMATION = 212
    SUBJECT_REPORT_EVALUATION = 213
    SUBJECT_HELP = 214
    
    SUBJECT_UNCAUGHT_CASE = 301
    
    CHOICES_SUBJECT_SENDING = (
        (SUBJECT_EMPTY, "---------"),
        (SUBJECT_REQUEST_FORM, "Requesting Form"),
        (SUBJECT_REQUEST_DOCUMENT, "Requesting Document"),
        (SUBJECT_SUBMIT_DOCUMENT, "Submitting Document"),
    )
    
    
    CHOICES_SUBJECT_RECEIVING = (
        (SUBJECT_RECEIVE_FORM, "Assigning Form"),
        (SUBJECT_RECEIVE_DOCUMENT, "Assigning Document"),
        (SUBJECT_ERROR, "Error"),
        (SUBJECT_INFORMATION, "Information"),
        (SUBJECT_REPORT_EVALUATION, "Evaluation Result"),
        (SUBJECT_HELP, "Help"),
        (SUBJECT_UNCAUGHT_CASE, "dfjhsjdvnvewe;efhjk")
    )
    
    CHOICES_SUBJECT = CHOICES_SUBJECT_SENDING + CHOICES_SUBJECT_RECEIVING
    
    BODY_UNCAUGHT_CASE = -1
    BODY_ERROR_NO_SUBJECT = 0
    
    BODY_ERROR_MISSING_FORM = 10
    BODY_ERROR_MISSING_DOCUMENT = 11
    BODY_ERROR_MISSING_UNIT = 12
    
    BODY_ERROR_WRONG_UNIT = 20
    BODY_ERROR_WRONG_FORM = 21
    BODY_ERROR_WRONG_DOCUMENT = 22
    
    BODY_ERROR_REDUNDANT_DOCUMENT = 30
        
    BODY_ERROR_UNFOUND_FORM = 40
    BODY_ERROR_UNFOUND_DOCUMENT = 41
    
    BODY_ERROR_EXISTING_FORM = 50
    BODY_ERROR_EXISTING_DOCUMENT = 51
    
    BODY_ERROR_LACKING_TRUST = 60
    
    BODY_ASSIGNING_FORM = 100
    BODY_ASSIGNING_DOCUMENT = 101
    
    BODY_REPORT_FAIL = 110
    BODY_REPORT_SUCCESS = 111
    
    BODY_PERFORMANCE_REPORT = 120
    
    BODY_TUTORIAL_1_INTRO = 210
    BODY_TUTORIAL_2_DOCUMENT_REQUEST = 220
    BODY_TUTORIAL_3_TASK_COMPLETION = 230
    BODY_TUTORIAL_4a_INCORRECT_MODIFICATION = 241
    BODY_TUTORIAL_4b_INCORRECT_MODIFICATION_2 = 242
    BODY_TUTORIAL_4c_CORRECT_MODIFICATION = 243
    BODY_TUTORIAL_5_CONCLUSION = 250
    
    CHOICES_BODY_TYPE = (
        (BODY_UNCAUGHT_CASE, 'BODY_UNCAUGHT_CASE'),
        (BODY_ERROR_NO_SUBJECT, 'BODY_ERROR_NO_SUBJECT'),
        (BODY_ERROR_MISSING_FORM, 'BODY_ERROR_MISSING_FORM'),
        (BODY_ERROR_MISSING_DOCUMENT, 'BODY_ERROR_MISSING_DOCUMENT'),
        (BODY_ERROR_MISSING_UNIT, 'BODY_ERROR_MISSING_UNIT'),
        (BODY_ERROR_WRONG_UNIT, 'BODY_ERROR_WRONG_UNIT'),
        (BODY_ERROR_WRONG_FORM, 'BODY_ERROR_WRONG_FORM'),
        (BODY_ERROR_WRONG_DOCUMENT, 'BODY_ERROR_WRONG_DOCUMENT'),
        (BODY_ERROR_REDUNDANT_DOCUMENT, 'BODY_ERROR_REDUNDANT_DOCUMENT'),
        (BODY_ERROR_UNFOUND_FORM, 'BODY_ERROR_UNFOUND_FORM'),
        (BODY_ERROR_UNFOUND_DOCUMENT, 'BODY_ERROR_UNFOUND_DOCUMENT'),
        (BODY_ERROR_EXISTING_FORM, 'BODY_ERROR_EXISTING_FORM'),
        (BODY_ERROR_EXISTING_DOCUMENT, 'BODY_ERROR_EXISTING_DOCUMENT'),
        (BODY_ERROR_LACKING_TRUST, 'BODY_ERROR_LACKING_TRUST'),
        (BODY_ASSIGNING_FORM, 'BODY_ASSIGNING_FORM'),
        (BODY_ASSIGNING_DOCUMENT, 'BODY_ASSIGNING_DOCUMENT'), 
        (BODY_REPORT_FAIL, 'BODY_REPORT_FAIL'),
        (BODY_REPORT_SUCCESS, 'BODY_REPORT_SUCCESS'),
        (BODY_PERFORMANCE_REPORT, 'BODY_PERFORMANCE_REPORT'),
        (BODY_TUTORIAL_1_INTRO, 'BODY_TUTORIAL_1_INTRO'),
        (BODY_TUTORIAL_2_DOCUMENT_REQUEST, 'BODY_TUTORIAL_2_DOCUMENT_REQUEST'),
        (BODY_TUTORIAL_3_TASK_COMPLETION, 'BODY_TUTORIAL_3_TASK_COMPLETION'),
        (BODY_TUTORIAL_4a_INCORRECT_MODIFICATION, 'BODY_TUTORIAL_4a_INCORRECT_MODIFICATION'),
        (BODY_TUTORIAL_4b_INCORRECT_MODIFICATION_2, 'BODY_TUTORIAL_4b_INCORRECT_MODIFICATION_2'),
        (BODY_TUTORIAL_4c_CORRECT_MODIFICATION, 'BODY_TUTORIAL_4c_CORRECT_MODIFICATION'),
        (BODY_TUTORIAL_5_CONCLUSION, 'BODY_TUTORIAL_5_CONCLUSION'),
    )
    
    mop = models.ForeignKey(Mop)
    unit = models.ForeignKey(Unit, blank=True, null=True)

    subject = models.IntegerField(choices=CHOICES_SUBJECT, default=SUBJECT_EMPTY, blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    read = models.BooleanField(default=False)
    state = models.IntegerField(choices=CHOICES_STATE, default=STATE_NORMAL)
    type = models.IntegerField(choices=CHOICES_TYPE)
    processed = models.BooleanField(default=False)
    trust = models.IntegerField(blank=True, null=True)
    bodyType = models.IntegerField(choices=CHOICES_BODY_TYPE, blank=True, null=True)
    replyTo = models.ForeignKey('self', blank=True, null=True)
    trustInstance = models.ForeignKey(TrustInstance, blank=True, null=True)
    
    requisitionBlank = models.ForeignKey(RequisitionBlank, null=True, blank=True)
    requisitionInstance = models.ForeignKey(RequisitionInstance, null=True, blank=True)
    mopDocumentInstance = models.ForeignKey(MopDocumentInstance, null=True, blank=True)
    
    createdAt = CreationDateTimeField()
    modifiedAt = ModificationDateTimeField()
    
    def generateBody(self):
        try:
            data = self.replyTo.requisitionInstance.data
        except:
            data = None
        
        text = None
        template = None
        tutorialData = {}
        tutorialData['mopco'] = Unit.objects.get(type=Unit.TYPE_COMMUNICATIVE)
    
        if self.bodyType == self.BODY_UNCAUGHT_CASE:
            template = loader.get_template('mop/mail/uncaught_case.txt')
        elif self.bodyType == self.BODY_ERROR_NO_SUBJECT:
            text = self.unit.mail_error_no_subject
        elif self.bodyType == self.BODY_ERROR_MISSING_FORM:
            text = self.unit.mail_error_missing_form
        elif self.bodyType == self.BODY_ERROR_MISSING_DOCUMENT:
            text = self.unit.mail_error_missing_document
        elif self.bodyType == self.BODY_ERROR_MISSING_UNIT:
            template = loader.get_template('mop/mail/no_unit.txt')
        elif self.bodyType == self.BODY_ERROR_WRONG_UNIT:
            text = self.unit.mail_error_wrong_unit
        elif self.bodyType == self.BODY_ERROR_WRONG_FORM:
            text = self.unit.mail_error_wrong_form
        elif self.bodyType == self.BODY_ERROR_WRONG_DOCUMENT:
            text = self.unit.mail_error_wrong_document
        elif self.bodyType == self.BODY_ERROR_REDUNDANT_DOCUMENT:
            text = self.unit.mail_error_redundant_document
        elif self.bodyType == self.BODY_ERROR_UNFOUND_FORM:
            text = self.unit.mail_error_unfound_form
        elif self.bodyType == self.BODY_ERROR_UNFOUND_DOCUMENT:
            text = self.unit.mail_error_unfound_document
        elif self.bodyType == self.BODY_ERROR_EXISTING_FORM:
            text = self.unit.mail_error_existing_form
        elif self.bodyType == self.BODY_ERROR_EXISTING_DOCUMENT:
            text = self.unit.mail_error_existing_document
        elif self.bodyType == self.BODY_ERROR_LACKING_TRUST:
            text = self.unit.mail_error_lacking_trust
        elif self.bodyType == self.BODY_ASSIGNING_FORM:
            text = self.unit.mail_assigning_form
        elif self.bodyType == self.BODY_ASSIGNING_DOCUMENT:
            text = self.unit.mail_assigning_document
        elif self.bodyType == self.BODY_REPORT_FAIL:
            text = self.unit.mail_report_fail
        elif self.bodyType == self.BODY_REPORT_SUCCESS:
            text = self.unit.mail_report_success
        elif self.bodyType == self.BODY_PERFORMANCE_REPORT:
            template = loader.get_template('mop/mail/performance_report.txt')
            data = self.trustInstance
        elif self.bodyType == self.BODY_TUTORIAL_1_INTRO:
            template = loader.get_template('mop/mail/tutorial_1_intro.txt')
            tutorialData['document_requisition'] = Requisition.objects.get(type=Requisition.TYPE_TUTORIAL)
            tutorialData['form_requisition'] = Requisition.objects.get(type=Requisition.TYPE_INITIAL)
        elif self.bodyType == self.BODY_TUTORIAL_2_DOCUMENT_REQUEST:
            template = loader.get_template('mop/mail/tutorial_2_document_request.txt')
            tutorialData['document'] = RandomizedDocument.objects.get(isTutorial=True)
            tutorialData['requisition'] = Requisition.objects.get(type=Requisition.TYPE_TUTORIAL)
        elif self.bodyType == self.BODY_TUTORIAL_3_TASK_COMPLETION:
            template = loader.get_template('mop/mail/tutorial_3_task_completion.txt')
        elif self.bodyType == self.BODY_TUTORIAL_4a_INCORRECT_MODIFICATION:
            template = loader.get_template('mop/mail/tutorial_4a_incorrect_modification.txt')
        elif self.bodyType == self.BODY_TUTORIAL_4b_INCORRECT_MODIFICATION_2:
            template = loader.get_template('mop/mail/tutorial_4b_incorrect_modification_2.txt')
        elif self.bodyType == self.BODY_TUTORIAL_4c_CORRECT_MODIFICATION:
            template = loader.get_template('mop/mail/tutorial_4c_correct_modification.txt')
            tutorialData['document'] = RandomizedDocument.objects.get(isTutorial=True)
        elif self.bodyType == self.BODY_TUTORIAL_5_CONCLUSION:
            template = loader.get_template('mop/mail/tutorial_5_conclusion.txt')
        else:
            text = self.get_bodyType_display()
        
        c = Context({"data": data, "tutorialData":tutorialData})    
        if not template == None:
            output = template.render(c)
        else :
            t = Template(text)
            output = t.render(c)
        
        return output
    
    def __unicode__(self):
        if self.subject == None:
            subject = "no subject"
        else:
            subject = self.get_subject_display()
        if self.type == self.TYPE_RECEIVED:
            try:
                sender = self.unit.serial
            except:
                sender = None
            receiver = self.mop.user.username
            sender_receiver = "%s to %s" % (sender, receiver)
            state = "read: %s" % self.read 
        elif self.type == self.TYPE_SENT:
            try:
                receiver = self.unit.serial
            except:
                receiver = None
            sender = self.mop.user.username
            sender_receiver = "%s to %s" % (sender, receiver)
            state = "processed: %s" % self.processed
        elif self.type == self.TYPE_DRAFT:
            sender = self.mop.user.username
            sender_receiver = "draft by %s" % sender
            state = ""
            
        return "%s - %s - %s - %s" % (sender_receiver, subject, self.trust, state)


